# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifications.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'notifications.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13notifications.proto\x12\rnotifications\"8\n\x12SendMessageRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x13SendMessageResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04info\x18\x02 \x01(\t\"+\n\x16GetClientStatusRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x92\x01\n\x17GetClientStatusResponse\x12\x46\n\x08statuses\x18\x01 \x03(\x0b\x32\x34.notifications.GetClientStatusResponse.StatusesEntry\x1a/\n\rStatusesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xcd\x01\n\x13NotificationService\x12T\n\x0bSendMessage\x12!.notifications.SendMessageRequest\x1a\".notifications.SendMessageResponse\x12`\n\x0fGetClientStatus\x12%.notifications.GetClientStatusRequest\x1a&.notifications.GetClientStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifications_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCLIENTSTATUSRESPONSE_STATUSESENTRY']._loaded_options = None
  _globals['_GETCLIENTSTATUSRESPONSE_STATUSESENTRY']._serialized_options = b'8\001'
  _globals['_SENDMESSAGEREQUEST']._serialized_start=38
  _globals['_SENDMESSAGEREQUEST']._serialized_end=94
  _globals['_SENDMESSAGERESPONSE']._serialized_start=96
  _globals['_SENDMESSAGERESPONSE']._serialized_end=143
  _globals['_GETCLIENTSTATUSREQUEST']._serialized_start=145
  _globals['_GETCLIENTSTATUSREQUEST']._serialized_end=188
  _globals['_GETCLIENTSTATUSRESPONSE']._serialized_start=191
  _globals['_GETCLIENTSTATUSRESPONSE']._serialized_end=337
  _globals['_GETCLIENTSTATUSRESPONSE_STATUSESENTRY']._serialized_start=290
  _globals['_GETCLIENTSTATUSRESPONSE_STATUSESENTRY']._serialized_end=337
  _globals['_NOTIFICATIONSERVICE']._serialized_start=340
  _globals['_NOTIFICATIONSERVICE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
