name: Python gRPC Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio allure-pytest grpcio grpcio-tools

    - name: Run tests with pytest and allure
      run: |
        pytest --alluredir=allure-results

    - name: Upload allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
